# General
general:
  test_id: "---"
  test_type: TL
  seed: 1

# Model parameters.
model:
  feature_extractor_arch: "resnet18"
  bow_extractor_opts:
    num_words: 8192
  num_classes: 24
  emb_width: 512
  pretraining: simclr
  mode: freezed
  cp_path: ../simclr/simclr_1/checkpoints-epoch=029-loss=1.042.ckpt
  alpha: True
  alpha_value: 1.0
  emb_type: "avg" # ["average", "sampling"]
  samples: 10

# Optimization parameters.
optim:
  optim_type: "sgd"
  momentum: 0.9
  weight_decay: 0.0001
  nesterov: False
  num_epochs: 30
  lr: 0.6
  beta: [0.9, 0.999]
  end_lr: 0.0015
  lr_schedule_type: "cos_warmup"
  step: 10
  gamma: 0.1
  patience: 10
  warmup_epochs: 10
  warmup_start_lr: 0.15
  alpha_min: 1.0
  alpha_max: 5.0
  loss:
    loss_type: bhtl 
    margin: 0.2
    squared: False
    mining: hard
    distance: LpDistance # [LpDistance, DotProductSimilarity]
    normalize_embedding: True
    p: 2
    power: 1
    ia_c_var_min: True
    iacvm_magnitude: 10
  same_authors: False

# Data parameters:
data:
  batch_size: 512
  transforms:
    img_crop_size: 380
    rc_p: 1.0
    cjitter:
      'brightness': [0.4, 1.3]
      'contrast': 0.6 
      'saturation': 0.6
      'hue': 0.4
    cjitter_p: 1
    randaffine:
      'degrees': [-10,10]
      'translate': [0.2, 0.2]
      'scale': [1.3, 1.4]
      'shear': 1
    randpersp:
      'distortion_scale': 0.1
      'p': 0.2
    gray_p: 0.2
    gaussian_blur:
      'kernel_size': 3
      'sigma': [0.1, 0.5]
    rand_eras:
      'p': 0.5
      'scale': [0.02, 0.33]
      'ratio': [0.3, 3.3]
      'value': 0
    invert_p: 0.05
    gaussian_noise:
      'mean': 0.0
      'std': 0.004
    gn_p: 0.0
    n_test_crops: 10
  weighted_sampling: True

# Test parameters
test:
  ratio_train: 20
  ratio_val: 40